// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.PowerUp.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1891.PowerUp.Robot;
import org.usfirst.frc1891.PowerUp.subsystems.DriveSystem;
import org.usfirst.frc1891.PowerUp.subsystems.DriveSystem.DriveTrainControlMode;

/**
 *
 */
public class Turn extends Command {

	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	private double target;
	private Timer startup;
	private boolean hasRun = false;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Turn(double inputTarget) {
    	target = inputTarget;
    	startup = new Timer();
    	requires(Robot.driveSystem);
    	

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if (!hasRun) {
    		startup.start();
    		
	    	Robot.driveSystem.setControlMode(DriveTrainControlMode.TurnInPlace);
	    	System.out.println("Target: " + target);
	    	Robot.driveSystem.setTurnTarget(target);
	    	
	    	System.out.println("Position: " + Robot.driveSystem.getNavxReading());
	    	System.out.println("Error: " + Robot.driveSystem.getTurnError());
	    	
	    	Robot.driveSystem.startTurn();
	    	hasRun = true;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	return startup.hasPeriodPassed(0.25) && Robot.driveSystem.hasReachedTurnTarget();
//    	return (startup.hasPeriodPassed(0.5) && Robot.driveSystem.hasReachedMotionTarget());
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	startup.stop();
    	startup.reset();
    	
    	Robot.driveSystem.stopTurn();
    	
    	System.out.println("Turn finished");
    	System.out.println("Position: " + Robot.driveSystem.getNavxReading());
    	System.out.println("Error: " + Robot.driveSystem.getTurnError());
    	
    	hasRun = false;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	System.out.println("Turn Interupted");
    	end();
    }
}
